# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171205_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book_author',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
