# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='count',
            new_name='county',
        ),
    ]
