# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_download_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='book_author',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
